name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow on pushing to the main branch
  pull_request:
    branches:
      - main  # Also trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub (if you want to push the image to Docker Hub, you need to add secrets for Docker Hub credentials)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t mynginx-app .

      # Step 5: Optionally, push the Docker image to Docker Hub (if you want to use the image elsewhere)
      - name: Push the Docker image
        run: |
          docker push mynginx-app
        if: github.ref == 'refs/heads/main'

      # Step 6: Run the container to test if it's working
      - name: Test Nginx container
        run: |
          docker run -d -p 8080:80 mynginx-app
          curl http://localhost:8080

